version: '1.0'

services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Docker/frontend.dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5173:5173
    networks:
      - minha-rede
    depends_on:
      - backend
      
  backend: 
    container_name: backend
    build: 
      context: .
      dockerfile: Docker/backend.dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    networks:
      - minha-rede
    depends_on:
      - db
  
  db:
    container_name: db
    build: 
      context: ./Docker
      dockerfile: db.dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3306:3306
    volumes:
      - ./Docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - minha-rede
    
networks:
  minha-rede:
    driver: bridge

